### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by dujiahei** [VDelv/EEGLearn-Pytorch#1]
Thanks for your share! 
I meet some problem as follows when I use it.

1. The packages mkl-fft==1.0.15 in requirements.txt  is not support Python3.7
2. the shapes of self.Images are different, when different functons recall   __getitem__（）.
such as, (7, 202, 3, 32, 32)  or (202, 3, 32, 32).
3. the dimension of Images is not one, so the "image=Images[Patient_id==choosen_patient]" make some error.

Look forward to a new version code.

**Comment by VDelv** [comment]
Hi,

I am glad you find my repo useful.

1. I am working on a conda environment with python 3.7.5 and mkl-ff==1.0.15 and didn't have any issues. I checked and `pip install mkl fft==1.0.15` works.

2. The shape of Images can be different, it depends on the model you consider, e.g. the mean of the seven images or choosing them separately (single frame or multi-frame approach in the [article](https://arxiv.org/pdf/1511.06448.pdf). Also explained in the [notebook](https://github.com/VDelv/EEGLearn-Pytorch/blob/master/EEGLearn_ShortDemo.ipynb).

3. In this case, it considers the first axis/dimension. If you prefer Images[id] correspond to Images[Id, :, :, :]. So it is not supposed to make any errors.

Hope it helps you,

If not, could you send the error printscreens?

Best,

VD
