### ISSUE TITLE
Where is the Images data (format: .mat,  shape: (2670, 7, 3, 32, 32))?

### ISSUE THREAD

**Issue by homingZhang** [VDelv/EEGLearn-Pytorch#2]
Hello,
There is no Images data in the Sample data folder.
Could you please upload the data?
or 
Could you tell me where I could find the data? 
Thank you.

**Comment by VDelv** [comment]
Hi @homingZhang ,

Thanks for the remarks. 
I forgot to mention it in the github but it was not possible to put the images_time.mat in the repository, the file size being superior to 100.0 Mb. 

But you can directly generate the file by running the [Train.py](https://github.com/VDelv/EEGLearn-Pytorch/blob/master/Train.py) script. 

These images are generated from the feature matrices provided by P. Bashivan ([link](https://github.com/pbashivan/EEGLearn/tree/master/Sample%20data)) and represent the power spectral density for each electrode in different frequency bands. 

Don't hesitate if you have any questions. 

Best, 

Victor

**Comment by homingZhang** [comment]
Yes, you are right!  I found the "create_img" function.
Thank you so much!
Good luck.
